import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  de: {
    // Auth
    'login': 'Anmelden',
    'logout': 'Abmelden',
    'email': 'E-Mail',
    'password': 'Passwort',
    'loginFailed': 'Anmeldung fehlgeschlagen',
    'demoCredentials': 'Demo-Anmeldedaten',
    'selectRole': 'Bitte wählen Sie Ihre Rolle',
    
    // Roles
    'admin': 'Administrator',
    'teacher': 'Fahrlehrer',
    'student': 'Schüler',
    
    // Navigation
    'dashboard': 'Dashboard',
    'lessons': 'Theoriestunden',
    'practicalLessons': 'Praktische Fahrstunden',
    'students': 'Schüler',
    'teachers': 'Fahrlehrer',
    'appointments': 'Termine',
    'payments': 'Zahlungen',
    'progress': 'Fortschritt',
    'discussion': 'Diskussion',
    'calendar': 'Kalender',
    'shop': 'Shop',
    'success': 'Erfolg',
    'error': 'Fehler',
    
    // Dashboard
    'welcome': 'Willkommen',
    'totalStudents': 'Gesamtanzahl Schüler',
    'totalTeachers': 'Gesamtanzahl Fahrlehrer',
    'activeAccounts': 'Aktive Konten',
    'totalLessons': 'Theoriestunden',
    'assignedStudents': 'Zugewiesene Schüler',
    'completedLessons': 'Abgeschlossene Stunden',
    'upcomingAppointments': 'Kommende Termine',
    'accountValidity': 'Kontogültigkeit',
    
    // Lessons
    'recordedLessons': 'Aufgezeichnete Theoriestunden',
    'watchLesson': 'Stunde ansehen',
    'markComplete': 'Als abgeschlossen markieren',
    'completed': 'Abgeschlossen',
    'notCompleted': 'Nicht abgeschlossen',
    
    // Appointments
    'bookAppointment': 'Termin buchen',
    'appointmentHistory': 'Terminverlauf',
    'date': 'Datum',
    'time': 'Uhrzeit',
    'status': 'Status',
    'approved': 'Genehmigt',
    'pending': 'Ausstehend',
    'cancelled': 'Storniert',
    'approve': 'Genehmigen',
    'cancel': 'Stornieren',
    'scheduled': 'Geplant',
    'duration': 'Dauer',
    'ticketsUsed': 'Verwendete Tickets',
    'tickets': 'Tickets',
    'remainingTickets': 'Verbleibende Tickets',
    'minutes': 'Minuten',
    'min': 'Min.',
    'createAppointment': 'Termin erstellen',
    'manageAppointments': 'Schülertermine verwalten',
    'viewAppointments': 'Ihre Termine anzeigen',
    'startTime': 'Startzeit',
    'durationMinutes': 'Dauer (Minuten)',
    'willUseTickets': 'Verwendet {count} Ticket(s)',
    'appointmentCreated': 'Termin erfolgreich erstellt',
    'appointmentUpdated': 'Termin erfolgreich aktualisiert',
    'appointmentCancelled': 'Termin storniert. Tickets wurden an den Schüler zurückgegeben.',
    'appointmentDeleted': 'Termin gelöscht. Tickets wurden an den Schüler zurückgegeben.',
    'appointmentCompleted': 'Termin als abgeschlossen markiert',
    'editAppointment': 'Termin bearbeiten',
    'updateAppointmentDetails': 'Termindetails aktualisieren. Die Ticketanzahl wird automatisch angepasst.',
    'cancelAppointment': 'Termin stornieren',
    'cancelAppointmentDescription': 'Termin stornieren. Tickets werden an den Schüler zurückgegeben. Stornierungsgrund ist erforderlich.',
    'cancelReason': 'Stornierungsgrund',
    'cancelReasonRequired': 'Stornierungsgrund *',
    'cancelReasonPlaceholder': 'Grund für die Stornierung eingeben...',
    'markAsCompleted': 'Genehmigen / Als abgeschlossen markieren',
    'cannotUndoApproval': 'Diese Aktion kann von Ihnen nicht rückgängig gemacht werden',
    'confirmCompletion': 'Termin als abgeschlossen markieren? Diese Aktion kann von Ihnen nicht rückgängig gemacht werden. Nur ein Administrator kann dies rückgängig machen.',
    'confirmDelete': 'Sind Sie sicher, dass Sie diesen Termin löschen möchten? Tickets werden an den Schüler zurückgegeben.',
    'pleaseFillFields': 'Bitte füllen Sie alle erforderlichen Felder aus',
    'notEnoughTickets': 'Der Schüler hat nicht genügend Tickets',
    'scheduledAppointments': 'Geplante Termine',
    'cancelledAppointments': 'Stornierte Termine',
    'allUpcomingAppointments': 'Alle bevorstehenden Termine',
    'appointmentsForSelectedDate': 'Termine für das ausgewählte Datum',
    'appointmentsCalendar': 'Terminkalender',
    'noAppointmentsOnDate': 'Keine Termine an diesem Datum',
    'selectDateToView': 'Wählen Sie ein Datum aus, um Termine anzuzeigen',
    'datesWithAppointments': 'Termine mit Terminen sind hervorgehoben',
    'noUpcomingAppointments': 'Keine bevorstehenden Termine',
    'totalScheduled': 'Gesamt: {count} geplant',
    'noAppointmentsFound': 'Keine Termine gefunden. Ihr Lehrer wird Termine für Sie erstellen.',
    'unknownStudent': 'Unbekannter Schüler',
    'unknownTeacher': 'Unbekannter Lehrer',
    'cancelledBy': 'Storniert von',
    'cancellationReason': 'Stornierungsgrund',
    'appointmentsForDate': 'Termine für ausgewähltes Datum',
    'viewAllAppointments': 'Alle Termine anzeigen',
    'studentStatistics': 'Schülerstatistiken',
    'overviewAppointmentsTickets': 'Übersicht der Termine und Tickets pro Schüler',
    'totalAppointments': 'Gesamttermine',
    'totalTicketsUsed': 'Verwendete Tickets',
    'isRequired': 'ist erforderlich',
    'createFirstAppointment': 'Keine Termine gefunden. Erstellen Sie Ihren ersten Termin oben.',
    'searchAppointments': 'Nach Schülername, Datum oder Uhrzeit suchen...',
    'filterByStatus': 'Nach Status filtern',
    'allStatuses': 'Alle Status',
    'appointment': 'Termin',
    'noAppointmentsFoundFilter': 'Keine Termine gefunden, die Ihrer Suche entsprechen.',
    'today': 'Heute',
    'tomorrow': 'Morgen',
    'yesterday': 'Gestern',
    'thisMonth': 'Dieser Monat',
    'selectedDate': 'Ausgewähltes Datum',
    'clear': 'Zurücksetzen',
    'at': 'um',
    'close': 'Schließen',
    'viewYourAppointments': 'Ihre Termine anzeigen',
    'reason': 'Grund',
    'unassigned': 'Nicht zugewiesen',
    'remaining': 'Verbleibend',
    
    // Payments
    'makePayment': 'Zahlung tätigen',
    'paymentHistory': 'Zahlungsverlauf',
    'amount': 'Betrag',
    'paymentStatus': 'Zahlungsstatus',
    'paid': 'Bezahlt',
    'exportReport': 'Bericht exportieren',
    
    // Common
    'save': 'Speichern',
    'cancelBtn': 'Abbrechen',
    'edit': 'Bearbeiten',
    'delete': 'Löschen',
    'view': 'Ansehen',
    'name': 'Name',
    'description': 'Beschreibung',
    'title': 'Titel',
    'message': 'Nachricht',
    'send': 'Senden',
    'back': 'Zurück',
    
    // Calendar
    'availability': 'Verfügbarkeit',
    'setAvailability': 'Verfügbarkeit festlegen',
    'teacherSchedule': 'Fahrlehrerplan',
    'selectDate': 'Datum auswählen',
    'selectTime': 'Zeit auswählen',
    'availableSlots': 'Verfügbare Slots',
    'book': 'Buchen',
    'available': 'Verfügbar',
    'booked': 'Gebucht',
    'addTimeSlot': 'Zeitslot hinzufügen',
    'removeSlot': 'Slot entfernen',
    'saveAvailability': 'Verfügbarkeit speichern',
    
    // Not Found
    'notFound': 'Nicht gefunden',
    'pageNotFound': 'Hoppla! Seite nicht gefunden',
    'returnHome': 'Zurück zur Startseite',
    
    // Practical Lessons
    'practicalLessonsTopics': 'Praktische Fahrstunden Themen',
    'managePracticalLessonsTopics': 'Verwalten Sie die Themen für praktische Fahrstunden',
    'addTopic': 'Thema hinzufügen',
    'topic': 'Thema',
    'topics': 'Themen',
    'editTopic': 'Thema bearbeiten',
    'addNewTopic': 'Neues Thema hinzufügen',
    'updateTopicDetails': 'Aktualisieren Sie die Themendetails',
    'createNewPracticalLessonTopic': 'Erstellen Sie ein neues Thema für praktische Fahrstunden',
    'nameGerman': 'Name (Deutsch)',
    'nameEnglish': 'Name (English)',
    'descriptionGerman': 'Beschreibung (Deutsch)',
    'descriptionEnglish': 'Beschreibung (English)',
    'category': 'Kategorie',
    'create': 'Erstellen',
    'areYouSure': 'Sind Sie sicher?',
    'cannotUndoAction': 'Diese Aktion kann nicht rückgängig gemacht werden. Dies wird das Thema permanent löschen.',
    'topicDeletedSuccessfully': 'Das Thema wurde erfolgreich gelöscht.',
    'topicUpdatedSuccessfully': 'Das Thema wurde erfolgreich aktualisiert.',
    'topicCreatedSuccessfully': 'Das neue Thema wurde erfolgreich erstellt.',
    'pleaseFillAllFields': 'Bitte füllen Sie alle erforderlichen Felder aus.',
    
    'manageLessonsForToday': 'Fahrstunden für heute verwalten und kommentieren',
    'addLesson': 'Fahrstunde hinzufügen',
    'noLessonsForThisDay': 'Keine Fahrstunden für diesen Tag eingetragen.',
    'selectStudentPlaceholder': 'Schüler auswählen',
    'selectTopicPlaceholder': 'Thema auswählen',
    'searchTopic': 'Thema suchen...',
    'noTopicFound': 'Kein Thema gefunden.',
    'comments': 'Kommentare',
    'commentsPlaceholder': 'Notizen zur Fahrstunde, Fortschritte, Verbesserungsvorschläge...',
    'pleaseSelectStudentAndTopic': 'Bitte wählen Sie einen Schüler und ein Thema aus.',
    'lessonUpdatedSuccessfully': 'Die Fahrstunde wurde erfolgreich aktualisiert.',
    'lessonCreatedSuccessfully': 'Die Fahrstunde wurde erfolgreich erstellt.',
    'editLesson': 'Fahrstunde bearbeiten',
    'addNewLesson': 'Neue Fahrstunde hinzufügen',
    'updateLessonDetails': 'Aktualisieren Sie die Fahrstundendetails',
    'recordLessonFor': 'Erfassen Sie eine Fahrstunde für',
    'recordNewLesson': 'Neue Fahrstunde erfassen',
    'viewBy': 'Ansicht',
    'dateWise': 'Nach Datum',
    'classWise': 'Nach Klasse',
    'pleaseSelectStudent': 'Bitte wählen Sie zuerst einen Schüler aus',
    'noLessonsForThisStudent': 'Keine Fahrstunden für diesen Schüler eingetragen',
    'noLessonsFound': 'Keine Fahrstunden gefunden',
    'lesson': 'Fahrstunde',
    'totalPracticalLessons': 'Gesamt Praktische Fahrstunden',
    'practicalLesson': 'Praktische Fahrstunde',
    'theoryLessons': 'Theoriestunden',
    'selectTopics': 'Themen auswählen',
    'selectTopicsPlaceholder': 'Themen auswählen (mehrere möglich)',
    'selected': 'ausgewählt',
    'pleaseSelectAtLeastOneTopic': 'Bitte wählen Sie mindestens ein Thema aus',
    'lessonsCreatedSuccessfully': '{count} Fahrstunde(n) erfolgreich erstellt',
    'pleaseSelectTopic': 'Bitte wählen Sie ein Thema aus',
    'deleteDateConfirm': 'Dies wird alle {count} Fahrstunde(n) für dieses Datum dauerhaft löschen. Diese Aktion kann nicht rückgängig gemacht werden.',
    'lessonsDeletedSuccessfully': '{count} Fahrstunde(n) erfolgreich gelöscht',
    'deletedSuccessfully': 'erfolgreich gelöscht',
    
    'myPracticalLessons': 'Meine Praktischen Fahrstunden',
    'overviewPracticalLessons': 'Übersicht aller praktischen Fahrstunden mit Themen und Kommentaren',
    'noPracticalLessonsYet': 'Noch keine praktischen Fahrstunden eingetragen.',
    'drivingLesson': 'Fahrstunde',
    'drivingLessons': 'Fahrstunden',
    'teacherComments': 'Kommentare des Fahrlehrers:',
    
    // Category labels
    'categoryGrundfahraufgabe': 'Grundfahraufgabe',
    'categorySonderfahrt': 'Sonderfahrt',
    'categoryStadtfahrt': 'Stadtfahrt',
    'categoryAutobahn': 'Autobahn',
    'categoryUeberland': 'Überland',
    'categoryBeleuchtung': 'Beleuchtung',
    'categoryParken': 'Parken',
    'categoryOther': 'Sonstiges',
    'unknown': 'Unbekannt',
    
    // Homepage
    'home': 'Startseite',
    'about': 'Über uns',
    'courses': 'Kurse',
    'theDrivingSchool': 'Die Fahrschule',
    'ourStory': 'Unsere Geschichte',
    'ourInstructors': 'Unsere Fahrlehrer',
    'ourLocations': 'Unsere Standorte',
    'azavCertification': 'AZAV Zertifizierung',
    'drivingLicense': 'Führerschein',
    'coursesAndDates': 'Kurse & Termine',
    'currentDates': 'Aktuelle Termine',
    'intensiveHolidayCourses': 'Intensiv-Ferienkurse',
    'theoryLessonsMenu': 'Theoriestunden',
    'practicalLessonsMenu': 'Praktische Fahrstunden',
    'examPreparation': 'Prüfungsvorbereitung',
    'prices': 'Preise',
    'locations': 'Standorte',
    'contact': 'Kontakt',
    'onlineRegistration': 'Online Anmeldung',
    'heroTitle1': 'Ihr Weg zum',
    'heroTitle2': 'Führerschein',
    'heroDescription': 'Moderne Fahrausbildung mit erfahrenen Fahrlehrern und flexiblen Kurszeiten. Starten Sie noch heute Ihre Fahrausbildung mit ByteTechnik Fahrschule.',
    'getStartedNow': 'Jetzt starten',
    'contactUs': 'Kontaktieren Sie uns',
    'expertInstructors': 'Erfahrene Fahrlehrer',
    'expertInstructorsDesc': 'Lernen Sie von zertifizierten Profis mit jahrelanger Lehrerfahrung',
    'flexibleSchedules': 'Flexible Zeiten',
    'flexibleSchedulesDesc': 'Wählen Sie aus Morgen-, Abend- und Wochenendkursen, die zu Ihrem Lebensstil passen',
    'highSuccessRate': 'Hohe Erfolgsquote',
    'highSuccessRateDesc': '95% unserer Schüler bestehen ihre Fahrprüfung beim ersten Versuch',
    'footerCopyright': '© 2024 ByteTechnik Fahrschule Management System. Alle Rechte vorbehalten.',
    'developedBy': 'Entwickelt von ByteTechnik',
  },
  en: {
    // Auth
    'login': 'Login',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'loginFailed': 'Login failed',
    'demoCredentials': 'Demo Login Credentials',
    'selectRole': 'Please choose your role',
    
    // Roles
    'admin': 'Administrator',
    'teacher': 'Driving Teacher',
    'student': 'Student',
    
    // Navigation
    'dashboard': 'Dashboard',
    'lessons': 'Theory Lessons',
    'practicalLessons': 'Practical Driving Lessons',
    'students': 'Students',
    'teachers': 'Teachers',
    'appointments': 'Appointments',
    'payments': 'Payments',
    'progress': 'Progress',
    'discussion': 'Discussion',
    'calendar': 'Calendar',
    'shop': 'Shop',
    'success': 'Success',
    'error': 'Error',
    
    // Dashboard
    'welcome': 'Welcome',
    'totalStudents': 'Total Students',
    'totalTeachers': 'Total Teachers',
    'activeAccounts': 'Active Accounts',
    'totalLessons': 'Theory Lessons',
    'assignedStudents': 'Assigned Students',
    'completedLessons': 'Completed Lessons',
    'upcomingAppointments': 'Upcoming Appointments',
    'accountValidity': 'Account Validity',
    
    // Lessons
    'recordedLessons': 'Recorded Theory Lessons',
    'watchLesson': 'Watch Lesson',
    'markComplete': 'Mark as Complete',
    'completed': 'Completed',
    'notCompleted': 'Not Completed',
    
    // Appointments
    'bookAppointment': 'Book Appointment',
    'appointmentHistory': 'Appointment History',
    'date': 'Date',
    'time': 'Time',
    'status': 'Status',
    'approved': 'Approved',
    'pending': 'Pending',
    'cancelled': 'Cancelled',
    'approve': 'Approve',
    'cancel': 'Cancel',
    'scheduled': 'Scheduled',
    'duration': 'Duration',
    'ticketsUsed': 'Tickets Used',
    'tickets': 'Tickets',
    'remainingTickets': 'Remaining Tickets',
    'minutes': 'minutes',
    'min': 'min',
    'createAppointment': 'Create Appointment',
    'manageAppointments': 'Manage student appointments',
    'viewAppointments': 'View your appointments',
    'startTime': 'Start Time',
    'durationMinutes': 'Duration (minutes)',
    'willUseTickets': 'Will use {count} ticket(s)',
    'appointmentCreated': 'Appointment created successfully',
    'appointmentUpdated': 'Appointment updated successfully',
    'appointmentCancelled': 'Appointment cancelled. Tickets have been returned to student.',
    'appointmentDeleted': 'Appointment deleted. Tickets have been returned to student.',
    'appointmentCompleted': 'Appointment marked as completed',
    'editAppointment': 'Edit Appointment',
    'updateAppointmentDetails': 'Update appointment details. Ticket count will be adjusted automatically.',
    'cancelAppointment': 'Cancel Appointment',
    'cancelAppointmentDescription': 'Cancel this appointment. Tickets will be returned to the student. Cancellation reason is required.',
    'cancelReason': 'Cancellation Reason',
    'cancelReasonRequired': 'Cancellation Reason *',
    'cancelReasonPlaceholder': 'Enter reason for cancellation...',
    'markAsCompleted': 'Approve / Mark as Completed',
    'cannotUndoApproval': 'This action cannot be undone by you',
    'confirmCompletion': 'Mark this appointment as completed? This action cannot be undone by you. Only admin can reverse it.',
    'confirmDelete': 'Are you sure you want to delete this appointment? Tickets will be returned to the student.',
    'pleaseFillFields': 'Please fill in all required fields',
    'notEnoughTickets': 'Student does not have enough tickets',
    'scheduledAppointments': 'Scheduled Appointments',
    'cancelledAppointments': 'Cancelled Appointments',
    'allUpcomingAppointments': 'All Upcoming Appointments',
    'appointmentsForSelectedDate': 'Appointments for Selected Date',
    'appointmentsCalendar': 'Appointments Calendar',
    'noAppointmentsOnDate': 'No appointments on this date',
    'selectDateToView': 'Select a date to view appointments',
    'datesWithAppointments': 'Dates with appointments are highlighted',
    'noUpcomingAppointments': 'No upcoming appointments',
    'totalScheduled': 'Total: {count} scheduled',
    'noAppointmentsFound': 'No appointments found. Your teacher will create appointments for you.',
    'unknownStudent': 'Unknown Student',
    'unknownTeacher': 'Unknown Teacher',
    'cancelledBy': 'Cancelled by',
    'cancellationReason': 'Cancellation Reason',
    'appointmentsForDate': 'Appointments for Selected Date',
    'viewAllAppointments': 'View all appointments and student statistics',
    'studentStatistics': 'Student Statistics',
    'overviewAppointmentsTickets': 'Overview of appointments and tickets per student',
    'totalAppointments': 'Total Appointments',
    'totalTicketsUsed': 'Tickets Used',
    'isRequired': 'is required',
    'createFirstAppointment': 'No appointments found. Create your first appointment above.',
    'searchAppointments': 'Search by student name, date, or time...',
    'filterByStatus': 'Filter by status',
    'allStatuses': 'All Statuses',
    'appointment': 'appointment',
    'noAppointmentsFoundFilter': 'No appointments found matching your search.',
    'today': 'Today',
    'tomorrow': 'Tomorrow',
    'yesterday': 'Yesterday',
    'thisMonth': 'This Month',
    'selectedDate': 'Selected Date',
    'clear': 'Clear',
    'at': 'at',
    'close': 'Close',
    'viewYourAppointments': 'View your appointments',
    'reason': 'Reason',
    'unassigned': 'Unassigned',
    'remaining': 'Remaining',
    
    // Payments
    'makePayment': 'Make Payment',
    'paymentHistory': 'Payment History',
    'amount': 'Amount',
    'paymentStatus': 'Payment Status',
    'paid': 'Paid',
    'exportReport': 'Export Report',
    
    // Common
    'save': 'Save',
    'cancelBtn': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'name': 'Name',
    'description': 'Description',
    'title': 'Title',
    'message': 'Message',
    'send': 'Send',
    'back': 'Back',
    
    // Calendar
    'availability': 'Availability',
    'setAvailability': 'Set Availability',
    'teacherSchedule': 'Teacher Schedule',
    'selectDate': 'Select Date',
    'selectTime': 'Select Time',
    'availableSlots': 'Available Slots',
    'book': 'Book',
    'available': 'Available',
    'booked': 'Booked',
    'addTimeSlot': 'Add Time Slot',
    'removeSlot': 'Remove Slot',
    'saveAvailability': 'Save Availability',
    
    // Not Found
    'notFound': 'Not Found',
    'pageNotFound': 'Oops! Page not found',
    'returnHome': 'Return to Home',
    
    // Practical Lessons
    'practicalLessonsTopics': 'Practical Driving Lesson Topics',
    'managePracticalLessonsTopics': 'Manage topics for practical driving lessons',
    'addTopic': 'Add Topic',
    'topic': 'Topic',
    'topics': 'Topics',
    'editTopic': 'Edit Topic',
    'addNewTopic': 'Add New Topic',
    'updateTopicDetails': 'Update topic details',
    'createNewPracticalLessonTopic': 'Create a new topic for practical driving lessons',
    'nameGerman': 'Name (German)',
    'nameEnglish': 'Name (English)',
    'descriptionGerman': 'Description (German)',
    'descriptionEnglish': 'Description (English)',
    'category': 'Category',
    'create': 'Create',
    'areYouSure': 'Are you sure?',
    'cannotUndoAction': 'This action cannot be undone. This will permanently delete the topic.',
    'topicDeletedSuccessfully': 'Topic has been successfully deleted.',
    'topicUpdatedSuccessfully': 'Topic has been successfully updated.',
    'topicCreatedSuccessfully': 'New topic has been successfully created.',
    'pleaseFillAllFields': 'Please fill in all required fields.',
    
    'manageLessonsForToday': 'Manage and comment on lessons for today',
    'addLesson': 'Add Lesson',
    'noLessonsForThisDay': 'No lessons recorded for this day.',
    'selectStudentPlaceholder': 'Select student',
    'selectTopicPlaceholder': 'Select topic',
    'searchTopic': 'Search topic...',
    'noTopicFound': 'No topic found.',
    'comments': 'Comments',
    'commentsPlaceholder': 'Notes on the lesson, progress, suggestions for improvement...',
    'pleaseSelectStudentAndTopic': 'Please select a student and a topic.',
    'lessonUpdatedSuccessfully': 'The lesson has been successfully updated.',
    'lessonCreatedSuccessfully': 'The lesson has been successfully created.',
    'editLesson': 'Edit Lesson',
    'addNewLesson': 'Add New Lesson',
    'updateLessonDetails': 'Update lesson details',
    'recordLessonFor': 'Record a lesson for',
    'recordNewLesson': 'Record new lesson',
    'viewBy': 'View By',
    'dateWise': 'By Date',
    'classWise': 'By Class',
    'pleaseSelectStudent': 'Please select a student first',
    'noLessonsForThisStudent': 'No lessons recorded for this student',
    'noLessonsFound': 'No lessons found',
    'lesson': 'lesson',
    'totalPracticalLessons': 'Total Practical Lessons',
    'practicalLesson': 'Practical Lesson',
    'theoryLessons': 'Theory Lessons',
    'selectTopics': 'Select Topics',
    'selectTopicsPlaceholder': 'Select topics (multiple allowed)',
    'selected': 'selected',
    'pleaseSelectAtLeastOneTopic': 'Please select at least one topic',
    'lessonsCreatedSuccessfully': '{count} lesson(s) created successfully',
    'pleaseSelectTopic': 'Please select a topic',
    'deleteDateConfirm': 'This will permanently delete all {count} lesson(s) for this date. This action cannot be undone.',
    'lessonsDeletedSuccessfully': '{count} lesson(s) deleted successfully',
    'deletedSuccessfully': 'deleted successfully',
    
    'myPracticalLessons': 'My Practical Driving Lessons',
    'overviewPracticalLessons': 'Overview of all practical driving lessons with topics and comments',
    'noPracticalLessonsYet': 'No practical driving lessons recorded yet.',
    'drivingLesson': 'driving lesson',
    'drivingLessons': 'driving lessons',
    'teacherComments': 'Teacher Comments:',
    
    // Category labels
    'categoryGrundfahraufgabe': 'Basic Driving Exercise',
    'categorySonderfahrt': 'Special Driving Lesson',
    'categoryStadtfahrt': 'City Driving',
    'categoryAutobahn': 'Highway',
    'categoryUeberland': 'Country Road',
    'categoryBeleuchtung': 'Lighting/Night',
    'categoryParken': 'Parking',
    'categoryOther': 'Other',
    'unknown': 'Unknown',
    
    // Homepage
    'home': 'Home',
    'about': 'About',
    'courses': 'Courses',
    'theDrivingSchool': 'The Driving School',
    'ourStory': 'Our Story',
    'ourInstructors': 'Our Instructors',
    'ourLocations': 'Our Locations',
    'azavCertification': 'AZAV Certification',
    'drivingLicense': 'Driving License',
    'coursesAndDates': 'Courses & Dates',
    'currentDates': 'Current Dates',
    'intensiveHolidayCourses': 'Intensive Holiday Courses',
    'theoryLessonsMenu': 'Theory Lessons',
    'practicalLessonsMenu': 'Practical Lessons',
    'examPreparation': 'Exam Preparation',
    'prices': 'Prices',
    'locations': 'Locations',
    'contact': 'Contact',
    'onlineRegistration': 'Online Registration',
    'heroTitle1': 'Your Journey to a',
    'heroTitle2': 'Driver\'s License',
    'heroDescription': 'Modern driving education with experienced instructors and flexible course schedules. Start your driving journey today with ByteTechnik Fahrschule.',
    'getStartedNow': 'Get Started Now',
    'contactUs': 'Contact Us',
    'expertInstructors': 'Expert Instructors',
    'expertInstructorsDesc': 'Learn from certified professionals with years of teaching experience',
    'flexibleSchedules': 'Flexible Schedules',
    'flexibleSchedulesDesc': 'Choose from morning, evening, and weekend classes that fit your lifestyle',
    'highSuccessRate': 'High Success Rate',
    'highSuccessRateDesc': '95% of our students pass their driving test on the first attempt',
    'footerCopyright': '© 2024 ByteTechnik Fahrschule Management System. All rights reserved.',
    'developedBy': 'Developed by ByteTechnik',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('de');

  useEffect(() => {
    const stored = localStorage.getItem('language') as Language;
    if (stored && (stored === 'de' || stored === 'en')) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
